### PR TITLE
feat: rename output APK with info about the build

### LINKED ISSUE #180: [Feature Request] Rename resulting file to actual app name
It would be nice to rename the resulting generated apk to actual name of the app.
Eg: instead of revanced.apk it could be: reddit 2022.28.0, YouTube Music 5.17.51 arm64 …

### PR DESCRIPTION
**Pull request by shrihanDev**
closes #180

### CODE REVIEW

**Comment by reisxd** [comment]
Does it use the old signature or creates a new one? (reading code on mobile is pain)

**Comment by shrihanDev** [comment]
> old signature

???

**Comment by reisxd** [comment]
> > old signature
> 
> ???

I mean, the old keystore file.

**Comment by shrihanDev** [comment]
> keystore file

That's up to ReVanced CLI... Wait, I get it, it always creates a new one based on the filename, shit.

**Comment by reisxd** [comment]
You can rename the app later or use the keystore flag.

**Comment by shrihanDev** [comment]
@reisxd Added a 'fix'.

**Comment by shrihanDev** [comment]
Btw,
> reading code on mobile is pain
Screenshot_2022-08-08-20-47-22-30
I wrote this on my mobile 🗿 

"Oh, I'm the king of patience and perseverance. `<insert Khalimov>` How'd you know?"

**Comment by reisxd** [comment]
> Btw,
> > reading code on mobile is pain
> 
> Screenshot_2022-08-08-20-47-22-30
> I wrote this on my mobile 🗿 
> 
> "Oh, I'm the king of patience and perseverance. `<insert Khalimov>` How'd you know?"

Makes me one of my friend, @VoltrexMaster (he used to code on his phone, until he got a laptop)

**Comment by shrihanDev** [comment]
Now he's contributing to nodejs and llvm 😱 :salute:

**Comment by reisxd** [comment]
> Now he's contributing to nodejs and llvm 😱🫡

Yep, he's really pog.

**Comment by reisxd** [comment]
@shrihanDev you

**Comment by shrihanDev** [comment]
:skull:

**Pull request merged**
