### PR TITLE
fix: bypass api rate limit if needed

### PR DESCRIPTION
**Pull request by TgSeed**
Bypasses the GH API rate limit if it's limited.
Bypass simply uses the GH web and extract the assets download links via regex from the response body.

### CODE REVIEW

**Comment by reisxd** [comment]
> > Please use cheerio. RegEx isn't a good solution for this. I get what it does but using cheerio would be better.
> 
> Interested to know why? Here are some pros of using Regex in here:
> 
> 1. DOM changes are more likely to happen than url by websites, so it will not break if GH changes design or codes.
> 2. Regex is faster than using cheerio, especially in this case. However, performance doesn't mean something for this project and scope.
> 3. Widely known by other developers than cheerio.
> 4. A built-in function, no bugs, no breaking changes, no changes.
> 
> Can you give the Cheerio query for this?

1: You are correct, but GitHub hasn't changed for a few months, you still can get the download URL if you get every single element that has the `data-skip-pjax` tag. 
2: I don't think using cheerio would make this like 999x slower, maybe by a few miliseconds.
3: Cheerio is also known, but this means nothing for the end user.
4: Cheerio also doesn't have bugs, no breaking changes (afaik) and also cheerio is already used for the YT APK scraper.
Also, your regex is... kinda broken (:
image

**Comment by TgSeed** [comment]
> 1: You are correct, but GitHub hasn't changed for a few months, you still can get the download URL if you get every single element that has the data-skip-pjax tag.

But means nothing in bigger and more popular projects, things most be coded like it should work for the lifetime.

> 2: I don't think using cheerio would make this like 999x slower, maybe by a few miliseconds.

True. again, things that matter on bigger projects, unlike this.



> Also, your regex is... kinda broken (: 
image

I recommend you reading more about [regex](https://duckduckgo.com/?q=Regex), especially the [regex groups](https://duckduckgo.com/?q=Regex+groups).
Thanks for the try anyway.

**Comment by reisxd** [comment]
> > 1: You are correct, but GitHub hasn't changed for a few months, you still can get the download URL if you get every single element that has the data-skip-pjax tag.
> 
> "But" means nothing in bigger and more popular projects, things must be coded like it should work for the lifetime.
> 
> > 2: I don't think using cheerio would make this like 999x slower, maybe by a few miliseconds.
> 
> True. again, things that matter on bigger projects, unlike this.
> 
> > Also, your regex is... kinda broken (:
> > image
> 
> I recommend you reading more about [regex](https://duckduckgo.com/?q=Regex), especially the [regex groups](https://duckduckgo.com/?q=Regex+groups). "This isn't working in that but how's it working in the pull request? uhhh another programming language bug..." Thanks for the try anyway.

Oh, looks like I was wrong. For some reason, the runtime returned that in the screenshot but it works... for some reason😅?
I sadly implemented that already though.

**Comment by TgSeed** [comment]
> I sadly implemented that already though.

Wish you have done that correctly, but you didn't.
If GH changes something tomorrow and your cheerio method fails to extract links, the whole process and program will fail silently or end up using older files! because you didn't handled that case where assetsGH.length is 0 before assigning to asset.
You're welcome.

**Pull request closed without merging**
