### PR TITLE
feat: tiktok support

### PR DESCRIPTION
**Pull request by ActuallyTheSun**

### CODE REVIEW

**Comment by reisxd** [comment]
pain

**Comment by reisxd** [comment]
> > pain
> 
> You made me a, you made me a believer; Believer!

:moyai: :skull:

**Comment by reisxd** [comment]
> Screenshot_20220816-213547_Aliucord
> 

shush

**Comment by shrihanDev** [comment]
> shush

Shut up, and bend over.

**Comment by reisxd** [comment]
> > shush
> 
> Shut up, and bend over.

ayooo chill im 14

**Comment by shrihanDev** [comment]
> ayooo chill im 14

I'm 14 too! ❤️💀

**Comment by reisxd** [comment]
> > ayooo chill im 14
> 
> I'm 14 too! ❤️💀

Then what's your `gender` property

**Comment by shrihanDev** [comment]
> Then what's your `gender` property

```javascript
> console.log(me.gender);
"Male"
```

**Comment by reisxd** [comment]
> > Then what's your `gender` property
> 
> ```javascript
> > console.log(me.gender);
> "Male"
> ```

I'd rather ```js
process.exit(97422974);
```

**Comment by shrihanDev** [comment]
> I'd rather
> 
> ```js
> process.exit(97422974);
> ```

```javascript
process.on('SIGTERM', () => void(0));
```

**Comment by reisxd** [comment]
> > I'd rather
> > 
> > ```js
> > process.exit(97422974);
> > ```
> 
> ```javascript
> process.on('SIGTERM', () => void(0));
> ```

I have an another trick,
```js
process.reallyExit(97422974);
```
That's a native function :trollface:

**Comment by shrihanDev** [comment]
Gone. Reduced to atoms!

**Comment by reisxd** [comment]
> Gone. Reduced to atoms!

what

**Comment by shrihanDev** [comment]
> > Gone. Reduced to atoms!
> 
> what

https://knowyourmeme.com/memes/gone-reduced-to-atoms

**Comment by reisxd** [comment]
> > > Gone. Reduced to atoms!
> > 
> > what
> 
> https://knowyourmeme.com/memes/gone-reduced-to-atoms

then i won :trollface:

**Pull request merged**
