### PR TITLE
Adding Docker File :) its working.......

### PR DESCRIPTION
**Pull request by vo1d-7bin**
U can check it [here](https://revanced.vo1d.cf/)
and more on my [repo](https://github.com/vo1d-7bin/docker-server-deploymen-revanced)

### CODE REVIEW

**Comment by shrihanDev** [comment]
It won't work sadly.
- Exposing the port 8000 might fail because other apps might be binding to that port
- Downloading doesn't work (in the website, didn't check the Dockerfile).

**Comment by vo1d-7bin** [comment]
[here](https://revanced.vo1d.cf/)
well the port issue is user problem 
and downloding issue( i was on my way to post it as a issue) I kinda solved u can look [here](https://app.vo1d.cf/)
[repo](https://github.com/vo1d-7bin/docker-server-deploymen-revanced)

**Comment by reisxd** [comment]
This shouldn't really be merged...

**Comment by vo1d-7bin** [comment]
> This shouldn't really be merged...

why not 😅
its running successfully without any error

**Comment by reisxd** [comment]
> > This shouldn't really be merged...
> 
> why not 😅 its running successfully without any error

It does not use the source version of Builder, installs unnecessary packages and it does not use `-no-open` flag.

**Comment by vo1d-7bin** [comment]
> > > This shouldn't really be merged...
> > 
> > why not 😅 its running successfully without any error
> 
> It does not use the source version of Builder, installs unnecessary packages and it does not use `-no-open` flag.

just checking [this](https://revanced.vo1d.cf)
and the app achive [here](https://app.vo1d.cf/)

**Pull request merged**
